In [1]:
import pandas as pd
import ast
import numpy as np
import tensorflow as tf
from tensorflow import keras
import keras_tuner as kt
from sklearn.model_selection import train_test_split

userDF = pd.read_csv("profiles.csv")
animeDF = pd.read_csv("animes.csv")
reviewsDF = pd.read_csv("reviews.csv")  
animeDF = animeDF.drop_duplicates(subset=['animeID'])
userDF = userDF.drop_duplicates(subset=['profile'])
userDF = userDF[userDF['favorite_animes']!='[]']


#que ni por el putas se toque esta función, muchas gracias :)

def get_favorite_genres(animeIDS):
    animeIDS = ast.literal_eval(animeIDS)
    returnGenres = set()
    for animeID in animeIDS:
        anime_row = animeDF[animeDF['animeID'] == animeID]
        if not anime_row.empty:
            genres = anime_row['genres'].str.split(',')
            for genre in genres:
                returnGenres.update(genre)
    return list(returnGenres)



def getOpinion(score):
    if score < 5:
        return -1
    if score >=5 and score < 7:
        return 0
    if score >=7:
        return 1
    
def vectorizeGenres(genresList, allGenres,n):
    returnArray = np.zeros(n)
    for genre in genresList:
        for i in range(0,len(allGenres),1):
            if genre == allGenres[i]:
                returnArray[i] = 1
    return returnArray

WARNING:tensorflow:From C:\Users\Jorge\anaconda3\envs\deep_learning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
animeDF

,animeID,title,genres
0,40960,Cheat Kusushi no Slow Life: Isekai ni Tsukurou...,"Comedy,Fantasy"
1,40957,Shin Chuuka Ichiban! 2,"Comedy,Shounen"
3,40956,Enen no Shouboutai: Ni no Shou,"Action,Supernatural,Shounen"
4,40938,Hige wo Soru. Soshite Joshikousei wo Hirou.,"Drama,Romance"
6,40936,Ore wo Suki nano wa Omae dake ka yo: Oretachi ...,"Comedy,Romance,School"
...,...,...,...
19221,8,Bouken Ou Beet,"Adventure,Fantasy,Shounen,Supernatural"
19222,7,Witch Hunter Robin,"Action,Magic,Police,Supernatural,Drama,Mystery"
19223,6,Trigun,"Action,Sci-Fi,Adventure,Comedy,Drama,Shounen"
19225,5,Cowboy Bebop: Tengoku no Tobira,"Action,Drama,Mystery,Sci-Fi,Space"
19227,1,Cowboy Bebop,"Action,Adventure,Comedy,Drama,Sci-Fi,Space"

In [3]:
userDF

,profile,gender,birthday,favorite_animes,link
0,DesolatePsyche,Male,"Oct 2,1994","[33352,25013,5530,33674,1482,269,18245,2904,27...",https://myanimelist.net/profile/DesolatePsyche
1,baekbeans,Female,"Nov 10,2000","[11061,31964,853,20583,918,9253,34599,3588,136...",https://myanimelist.net/profile/baekbeans
2,skrn,NaN,NaN,"[918,2904,11741,17074,23273,32281,9989,1943,512]",https://myanimelist.net/profile/skrn
3,edgewalker00,Male,Sep 5,"[5680,849,2904,3588,37349]",https://myanimelist.net/profile/edgewalker00
4,aManOfCulture99,Male,"Oct 30,1999","[4181,7791,9617,5680,2167,4382,849,235,35180,3...",https://myanimelist.net/profile/aManOfCulture99
...,...,...,...,...,...
77646,WeissYuki,NaN,NaN,"[36563,237,23273,32979,23283,12189,5114,4282]",https://myanimelist.net/profile/WeissYuki
77651,Akuteru,Male,"Aug 30,1993","[6624,20785,17265,28121]",https://myanimelist.net/profile/Akuteru
77652,Razielek,Male,"Nov 8,1986","[47,523,820,30,339]",https://myanimelist.net/profile/Razielek
77654,Mattierial,NaN,NaN,"[10087,21327,585,28851,32281,431,578,5114,1535]",https://myanimelist.net/profile/Mattierial
77657,bridgesams,Male,"Jan 1,2001","[37510,35180,30,31043,5081,37450,11843]",https://myanimelist.net/profile/bridgesams

In [4]:
reviewsDF

        reviewID          profile  animeID  score
0         255938   DesolatePsyche    34096      8
1         259117        baekbeans    34599     10
2         253664             skrn    28891      7
3           8254     edgewalker00     2904      9
4         291149  aManOfCulture99     4181     10
...          ...              ...      ...    ...
192107    240067       Unicorn819     1281      9
192108    285777        ShizzoSVH     1281      9
192109    286904        AlluMan96     1281      3
192110    287903        AgentK300     1281     10
192111    299323       Scarlet012     1281      9

[192112 rows x 4 columns]

In [5]:
userDF['favorite_genres']=userDF['favorite_animes'].apply(get_favorite_genres)
userDF

,profile,gender,birthday,favorite_animes,link,favorite_genres
0,DesolatePsyche,Male,"Oct 2,1994","[33352,25013,5530,33674,1482,269,18245,2904,27...",https://myanimelist.net/profile/DesolatePsyche,"[Martial Arts, Military, Vampire, Drama, Actio..."
1,baekbeans,Female,"Nov 10,2000","[11061,31964,853,20583,918,9253,34599,3588,136...",https://myanimelist.net/profile/baekbeans,"[Drama, Action, Shounen, Fantasy, Historical, ..."
2,skrn,NaN,NaN,"[918,2904,11741,17074,23273,32281,9989,1943,512]",https://myanimelist.net/profile/skrn,"[Military, Vampire, Drama, Action, Shounen, Fa..."
3,edgewalker00,Male,Sep 5,"[5680,849,2904,3588,37349]",https://myanimelist.net/profile/edgewalker00,"[Parody, Military, Super Power, Supernatural, ..."
4,aManOfCulture99,Male,"Oct 30,1999","[4181,7791,9617,5680,2167,4382,849,235,35180,3...",https://myanimelist.net/profile/aManOfCulture99,"[Parody, Seinen, Supernatural, Drama, Mystery,..."
...,...,...,...,...,...,...
77646,WeissYuki,NaN,NaN,"[36563,237,23273,32979,23283,12189,5114,4282]",https://myanimelist.net/profile/WeissYuki,"[Military, Drama, Action, Shounen, Fantasy, Su..."
77651,Akuteru,Male,"Aug 30,1993","[6624,20785,17265,28121]",https://myanimelist.net/profile/Akuteru,"[Super Power, Supernatural, Mystery, Adventure..."
77652,Razielek,Male,"Nov 8,1986","[47,523,820,30,339]",https://myanimelist.net/profile/Razielek,"[Military, Seinen, Space, Supernatural, Advent..."
77654,Mattierial,NaN,NaN,"[10087,21327,585,28851,32281,431,578,5114,1535]",https://myanimelist.net/profile/Mattierial,"[Historical, Military, Supernatural, Drama, Ad..."
77657,bridgesams,Male,"Jan 1,2001","[37510,35180,30,31043,5081,37450,11843]",https://myanimelist.net/profile/bridgesams,"[Seinen, Dementia, Vampire, Supernatural, Dram..."

In [6]:
columns_to_keep_from_user = ['profile','favorite_genres']
userDF = userDF[columns_to_keep_from_user]
userDF

               profile                                    favorite_genres
0       DesolatePsyche  [Martial Arts, Military, Vampire, Drama, Actio...
1            baekbeans  [Drama, Action, Shounen, Fantasy, Historical, ...
2                 skrn  [Military, Vampire, Drama, Action, Shounen, Fa...
3         edgewalker00  [Parody, Military, Super Power, Supernatural, ...
4      aManOfCulture99  [Parody, Seinen, Supernatural, Drama, Mystery,...
...                ...                                                ...
77646        WeissYuki  [Military, Drama, Action, Shounen, Fantasy, Su...
77651          Akuteru  [Super Power, Supernatural, Mystery, Adventure...
77652         Razielek  [Military, Seinen, Space, Supernatural, Advent...
77654       Mattierial  [Historical, Military, Supernatural, Drama, Ad...
77657       bridgesams  [Seinen, Dementia, Vampire, Supernatural, Dram...

[37463 rows x 2 columns]

In [7]:
reviewsDF['opinion'] = reviewsDF['score'].apply(getOpinion)
reviewsDF

        reviewID          profile  animeID  score  opinion
0         255938   DesolatePsyche    34096      8        1
1         259117        baekbeans    34599     10        1
2         253664             skrn    28891      7        1
3           8254     edgewalker00     2904      9        1
4         291149  aManOfCulture99     4181     10        1
...          ...              ...      ...    ...      ...
192107    240067       Unicorn819     1281      9        1
192108    285777        ShizzoSVH     1281      9        1
192109    286904        AlluMan96     1281      3       -1
192110    287903        AgentK300     1281     10        1
192111    299323       Scarlet012     1281      9        1

[192112 rows x 5 columns]

In [8]:
user_and_review = pd.merge(reviewsDF, userDF, on='profile')
user_and_review = user_and_review[['profile','favorite_genres','animeID','opinion']]
user_and_review

,profile,favorite_genres,animeID,opinion
0,DesolatePsyche,"[Martial Arts, Military, Vampire, Drama, Actio...",34096,1
1,DesolatePsyche,"[Martial Arts, Military, Vampire, Drama, Actio...",12403,0
2,DesolatePsyche,"[Martial Arts, Military, Vampire, Drama, Actio...",35073,0
3,DesolatePsyche,"[Martial Arts, Military, Vampire, Drama, Actio...",23225,1
4,DesolatePsyche,"[Martial Arts, Military, Vampire, Drama, Actio...",2035,1
...,...,...,...,...
161394,WeissYuki,"[Military, Drama, Action, Shounen, Fantasy, Su...",2593,1
161395,Akuteru,"[Super Power, Supernatural, Mystery, Adventure...",2593,1
161396,Razielek,"[Military, Seinen, Space, Supernatural, Advent...",2593,1
161397,Mattierial,"[Historical, Military, Supernatural, Drama, Ad...",2593,1
161398,bridgesams,"[Seinen, Dementia, Vampire, Supernatural, Dram...",2593,1

In [9]:
all_merged = pd.merge(user_and_review,animeDF, on = 'animeID')
all_merged = all_merged[['profile','favorite_genres','title','genres', 'opinion']]
all_merged

,profile,favorite_genres,title,genres,opinion
0,DesolatePsyche,"[Martial Arts, Military, Vampire, Drama, Actio...",Gintama.,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",1
1,DesolatePsyche,"[Martial Arts, Military, Vampire, Drama, Actio...",Gintama.,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",1
2,Injenss,"[Martial Arts, Military, Drama, Action, Shoune...",Gintama.,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",1
3,Injenss,"[Martial Arts, Military, Drama, Action, Shoune...",Gintama.,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",1
4,kokuborou,"[Martial Arts, Military, Space, Vampire, Drama...",Gintama.,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",1
...,...,...,...,...,...
161377,Anime_is_Life3,"[Supernatural, Adventure, Drama, Shoujo, Slice...",Yuki no Joou (TV),"Adventure,Drama,Fantasy,Shoujo",1
161378,Funnysmily,"[Military, Seinen, Adventure, Drama, Action, M...",Higepiyo,Comedy,1
161379,Intumesce,"[Space, Military, Seinen, Super Power, Drama, ...",Tantei Opera Milky Holmes Movie: Gyakushuu no ...,"Comedy,Mystery,Super Power",1
161380,paulthetallguy,"[Vampire, Drama, Action, Dementia, Supernatura...","Wake Up,Girls! Seishun no Kage","Drama,Music",1
161381,Rikudo134,"[Military, Vampire, Drama, Action, Shounen, Fa...",Rec: Yurusarezarumono,"Comedy,Drama,Romance,Seinen",1

In [10]:
all_genres = animeDF['genres'].str.split(',').explode()
all_genres = set(all_genres)
for genre in all_genres:
    print(genre)

Martial Arts
Military
Space
Vampire
Drama
Action
Shounen
Fantasy
Yuri
Historical
Super Power
Dementia
Supernatural
Adventure
Sports
Shoujo
Samurai
Psychological
Romance
Music
Horror
Game
Ecchi
Mecha
Comedy
Yaoi
Parody
Seinen
Hentai
Harem
Shounen Ai
Slice of Life
Demons
Magic
Sci-Fi
Thriller
School
Police
Cars
Kids
Josei
Mystery
Shoujo Ai

In [11]:
all_genres = np.array(list(all_genres))
n = len(all_genres)
all_merged['vectorized_favorite_genres'] = all_merged['favorite_genres'].apply(vectorizeGenres, args=(all_genres,n))

In [12]:
all_merged['vectorized_anime_genres'] = all_merged['genres'].str.split(',').apply(vectorizeGenres, args=(all_genres, n))

In [13]:
all_merged

,profile,favorite_genres,title,genres,opinion,vectorized_favorite_genres,vectorized_anime_genres
0,DesolatePsyche,"[Martial Arts, Military, Vampire, Drama, Actio...",Gintama.,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",1,"[1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ..."
1,DesolatePsyche,"[Martial Arts, Military, Vampire, Drama, Actio...",Gintama.,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",1,"[1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ..."
2,Injenss,"[Martial Arts, Military, Drama, Action, Shoune...",Gintama.,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",1,"[1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ..."
3,Injenss,"[Martial Arts, Military, Drama, Action, Shoune...",Gintama.,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",1,"[1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ..."
4,kokuborou,"[Martial Arts, Military, Space, Vampire, Drama...",Gintama.,"Action,Comedy,Historical,Parody,Samurai,Sci-Fi...",1,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...,...
161377,Anime_is_Life3,"[Supernatural, Adventure, Drama, Shoujo, Slice...",Yuki no Joou (TV),"Adventure,Drama,Fantasy,Shoujo",1,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, ..."
161378,Funnysmily,"[Military, Seinen, Adventure, Drama, Action, M...",Higepiyo,Comedy,1,"[0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
161379,Intumesce,"[Space, Military, Seinen, Super Power, Drama, ...",Tantei Opera Milky Holmes Movie: Gyakushuu no ...,"Comedy,Mystery,Super Power",1,"[0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
161380,paulthetallguy,"[Vampire, Drama, Action, Dementia, Supernatura...","Wake Up,Girls! Seishun no Kage","Drama,Music",1,"[0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ..."
161381,Rikudo134,"[Military, Vampire, Drama, Action, Shounen, Fa...",Rec: Yurusarezarumono,"Comedy,Drama,Romance,Seinen",1,"[0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ..."

In [14]:
columns_to_keep_from_all_merged = ['profile','vectorized_favorite_genres','title','vectorized_anime_genres','opinion']
all_merged = all_merged[columns_to_keep_from_all_merged]
all_merged

,profile,vectorized_favorite_genres,title,vectorized_anime_genres,opinion
0,DesolatePsyche,"[1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...",Gintama.,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",1
1,DesolatePsyche,"[1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...",Gintama.,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",1
2,Injenss,"[1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...",Gintama.,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",1
3,Injenss,"[1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...",Gintama.,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",1
4,kokuborou,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...",Gintama.,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",1
...,...,...,...,...,...
161377,Anime_is_Life3,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, ...",Yuki no Joou (TV),"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, ...",1
161378,Funnysmily,"[0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...",Higepiyo,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1
161379,Intumesce,"[0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, ...",Tantei Opera Milky Holmes Movie: Gyakushuu no ...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1
161380,paulthetallguy,"[0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, ...","Wake Up,Girls! Seishun no Kage","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...",1
161381,Rikudo134,"[0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...",Rec: Yurusarezarumono,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...",1

In [15]:
trainDF = all_merged[['vectorized_favorite_genres','vectorized_anime_genres','opinion']]
trainDF

,vectorized_favorite_genres,vectorized_anime_genres,opinion
0,"[1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",1
1,"[1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",1
2,"[1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",1
3,"[1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",1
4,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...",1
...,...,...,...
161377,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, ...",1
161378,"[0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1
161379,"[0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1
161380,"[0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...",1
161381,"[0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...",1

In [16]:
def train_val_test_split(df, rstate=42, shuffle=True, stratify=None):
    strat = df[stratify] if stratify else None
    train_set, test_set = train_test_split(
        df, test_size=0.4, random_state=rstate, shuffle=shuffle, stratify=strat)
    strat = test_set[stratify] if stratify else None
    val_set, test_set = train_test_split(
        test_set, test_size=0.5, random_state=rstate, shuffle=shuffle, stratify=strat)
    return (train_set, val_set, test_set)

def remove_labels(df, label_name):
    X = df.drop(label_name, axis=1)
    y = df[label_name].copy()
    return (X, y)

In [17]:
train_set, val_set, test_set = train_val_test_split(trainDF)

In [18]:
train_set

,vectorized_favorite_genres,vectorized_anime_genres,opinion
4901,"[0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, ...",1
90190,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...",1
27670,"[0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...",1
89659,"[0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, ...",1
159801,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1
...,...,...,...
119879,"[0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, ...",0
103694,"[0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...",1
131932,"[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, ...",1
146867,"[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...",1
121958,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...",1

In [28]:
X_train, y_train = remove_labels(train_set, 'opinion')
X_val, y_val = remove_labels(val_set, 'opinion')
X_test, y_test = remove_labels(test_set, 'opinion')

In [29]:
X_train= X_train.values
X_test= X_test.values
X_val = X_val.values

(96829, 2)

In [30]:
X_train

array([[array([0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
               1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
               1., 0., 1., 1., 0., 0., 0., 1., 0.])                               ,
        array([0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
               0., 0., 0., 0., 0., 0., 0., 0., 0.])                               ],
       [array([0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
               1., 0., 1., 0., 0., 0., 0., 0., 0.])                               ,
        array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 1., 0., 0., 0., 0., 0., 0.])                               ],
       [array([0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
               0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1.,
               1., 0., 1., 0., 0., 0., 0., 1., 0.])                               ,
        array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               1., 0., 0., 0., 0., 0., 0., 1., 0.])                               ],
       ...,
       [array([0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
               1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
               0., 1., 1., 0., 0., 0., 0., 1., 0.])                               ,
        array([0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 1., 0., 0., 0., 0., 0., 0.])                               ],
       [array([0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
               0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
               0., 0., 0., 1., 0., 0., 1., 1., 0.])                               ,
        array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
               0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 1., 0., 0., 0., 0., 0., 0.])                               ],
       [array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
               0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0.])                               ,
        array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
               0., 0., 0., 0., 0., 0., 0., 0., 0.])                               ]],
      dtype=object)